# Generated by Django 5.2.6 on 2025-10-23 10:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_participated', models.DateField(auto_now_add=True)),
                ('hours_completed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('joined', 'Joined'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='joined', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.event')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='api.volunteer')),
            ],
            options={
                'unique_together': {('volunteer', 'event')},
            },
        ),
    ]
