# Generated by Django 5.2.6 on 2025-10-29 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='api.organization'),
        ),
    ]
