# Generated by Django 5.2.6 on 2025-10-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_organization_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='certificate_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
