# Generated by Django 5.2.6 on 2025-11-07 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_participation_certificate_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('volunteer', 'organization')},
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='organizations',
        ),
        migrations.AddField(
            model_name='membership',
            name='join_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Volunteer'), ('executive', 'Executive'), ('admin', 'Admin')], default='volunteer', max_length=20),
        ),
        migrations.RemoveField(
            model_name='membership',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='verified',
        ),
    ]
