# Generated by Django 4.2.27 on 2026-02-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_membership_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
