from django.views.decorators.csrf import csrf_exempt
from django.urls import path
from backend import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('my-volunteer-data/', views.get_my_volunteer_data),
    path('my-admin-data/', views.get_my_admin_data),
    path('get-volunteer-data/<uuid:volunteer_id>/', views.get_volunteer_data_by_id),
    path('get-admin-data/<uuid:admin_id>/', views.get_admin_data_by_id),
    path('update-volunteer-data/', views.update_my_volunteer_data),
    path('update-admin-data/', views.update_my_admin_data),
    path('token/', views.CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', views.CustomTokenRefreshView.as_view(), name='token_refresh'),
    path('register/', views.register_user),
    path('register-organization/', views.register_organization),
    path('update-organization/', views.update_organization),
    path('authenticated/', views.authenticated),
    path('logout/', views.logout_user),
    path('organizations/join/', views.join_organization_by_code),
    path('approve_membership/<uuid:membership_id>/', views.approve_membership),
    path('reject_membership/<uuid:membership_id>/', views.reject_member),
    path('list_pending_members/', views.list_pending_members),
    path('organizations/quit/', views.quit_organization_by_code),
    path('get-my-events-as-volunteer/', views.get_my_events_as_volunteer),
    path('get-my-events-as-admin/', views.get_my_events_as_admin),
    path('create-event/', views.create_event),
    path('update-event/<uuid:event_id>/', views.update_event),
    path('delete-event/<uuid:event_id>/', views.delete_event),
    path('events/<uuid:event_id>/join/', views.join_event),
    path('events/<uuid:event_id>/cancel/', views.cancel_participation),
    path('participations-as-volunteer/', views.get_my_participations_as_volunteer),
    path('participations-as-admin/<uuid:event_id>/', views.get_participations_as_admin),
    path('participations/<uuid:participation_id>/complete/', views.mark_participation_completed),
    path('verify-email/', views.verify_email_code, name='verify-email'),
    path('resend-verification-code/', views.resend_verification_code, name='resend-verification-code'),
    path('analytics/volunteer-stats/', views.volunteer_stats),
    path('analytics/event-participation-stats/', views.event_participation_stats),
    path('analytics/my-volunteer-stats/', views.my_volunteer_stats),
    path('analytics/my-admin-stats/', views.my_admin_stats),
    path('analytics/my-organization-stats/', views.my_organization_stats),
    path('password-reset/', views.PasswordResetRequestView.as_view(), name='password-reset'),
    path('password-reset-confirm/', views.PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('generate-certificate/<uuid:participation_id>/', views.generate_certificate, name='generate-certificate'),
    path('generate-summary-certificate/', csrf_exempt(views.generate_summary_certificate_view), name='generate-summary-certificate'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)